accelerator: gpu
act: relu
ae_act: relu
ae_epochs: 100
ae_fn: ''
alpha: 1.0e-06
center_tolerance: 0.001
channels:
- 32
- 16
- 32
conv_oper: sagc
create_experiment_dir: true
data_dir: /home/isha_lodha/poselift-study/data_coskad/e1
dataset_batch_size: 2048
dataset_choice: HR-STC
dataset_double_item: false
dataset_headless: false
dataset_hip_center: false
dataset_kp18_format: false
dataset_kp_th: 0
dataset_normalization_strategy: markovitz
dataset_normalize_pose: true
dataset_num_transform: 5
dataset_num_workers: 8
dataset_path_to_robust: /home/isha_lodha/poselift-study/data_coskad/e1
dataset_return_indices: false
dataset_seg_len: 12
dataset_seg_stride: 1
dataset_seg_th: 0
dataset_start_offset: 0
dataset_sub_mean: false
dataset_symm_range: true
dataset_to_pow: false
dataset_use_fitted_scaler: false
dataset_vid_res:
- 1920
- 1080
debug: false
device: cuda
devices:
- 0
dir_name: e1_f6_s3
distance: euclidean
dropout: 0
encoder_type: STS_GCN
exp_dir: /home/isha_lodha/poselift-study/results/model_runs/coskad/e1/ckpt
group_name: stc
h_dim: 64
hyperbolic: false
lambda_: 0.01
latent_dim: 16
load_ckpt: ''
max_epochs: 100
num_coords: 2
opt_lr: 0.0001
opt_lr_decay: 0.99
opt_optimizer: adam
opt_scheduler: tri
opt_weight_decay: 1.0e-05
pad_size: 20
pretrained: false
project_name: coskad
projector: mlp
seed: 3
self_minimization: false
smoothing: 1
split: train
static_center: false
test_path: /home/isha_lodha/poselift-study/data_coskad/e1/testing/test_frame_mask
use_decoder: false
use_hr: false
use_vae: false
use_wandb: false
validation: false
viz_gif_folder: os.path.join(default_data_dir, 'viz')
wandb_entity: pinlab-sapienza
