accelerator: gpu
aggregation_strategy: best
batch_size: 4096
channels:
- 32
- 16
- 32
conditioning_architecture: AE
conditioning_indices:
- 0
- 1
- 2
conditioning_strategy: inject
create_experiment_dir: true
data_dir: /home/isha_lodha/poselift-study/data_mocodad/b
dataset_choice: HR-STC
debug: false
devices:
- 0
dir_name: b_s2
dropout: 0.0
embedding_dim: 16
exp_dir: /home/isha_lodha/poselift-study/results/model_runs/mocodad
filter_kernel_size: 15
frames_shift: 9
group_name: group_name
h_dim: 32
headless: false
hip_center: false
kp18_format: false
latent_dim: 16
load_ckpt: epoch=93-step=5076.ckpt
load_tensors: false
loss_fn: smooth_l1
model_return_value: loss
n_epochs: 100
n_generated_samples: 50
noise_steps: 10
normalization_strategy: robust
num_coords: 2
num_transform: 5
num_workers: 8
opt_lr: 0.0001
pad_size: -1
project_name: project_name
rec_weight: 1.0
save_tensors: false
seed: 0
seg_len: 6
seg_stride: 6
seg_th: 0
split: test
start_offset: 0
symm_range: true
test_path: /home/isha_lodha/poselift-study/data_mocodad/b/testing/test_frame_mask
use_ema: false
use_fitted_scaler: false
use_hr: false
use_wandb: false
validation: false
vid_res:
- 1920
- 1080
wandb_entity: entity_name
